version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      # Add any test commands here if you have tests
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app/**/*
    - requirements.txt
    - .ebextensions/**/*
    - .platform/**/*
  discard-paths: no
